### PR TITLE
Prepare project for PyPI and rename to agentspeak

### PR DESCRIPTION
**Pull request by javipalanca**
The structure of the project has been enriched with some cookiecutter goodies from https://github.com/audreyr/cookiecutter-pypackage. Some docs structure, makefile and travis files were included.
The project is now prepared to be synchronized with TravisCI for continuous integration and with  readthedocs for publishing documentation. It will be also prepared for coverage in the future.

The project has been renamed from pyson to agentspeak to avoid conflicts in PyPI.

It has also been code styled following the PEP8 style guide (https://www.python.org/dev/peps/pep-0008/).

Test have been ported too py.test.

### CODE REVIEW

**Comment by niklasf** [comment]
Thank you! I'll get to it soon-ish.

**Comment by javipalanca** [comment]
Hi @niklasf 
Any news about this PR? I have a student who would appreciate being able to install pyson (now python-agentspeak) for his master thesis which is being presented next month. If you think it is possible to accept the PR before that date it would be great, otherwise there is no problem of course!

**Comment by niklasf** [comment]
Oh, alright. I published a first version with part of these changes: https://pypi.org/project/agentspeak/

I'll come back and apply more of them later (travis, readthedocs, ...).

Also if your student is willing to share the thesis, I'd definitely be intrested to check it out.

**Comment by javipalanca** [comment]
Thank you so much. This is very helpful for my student.
Unfortunately he is writing the master thesis in spanish, but I'll tell you what is it about: we are adding BDI abilities to agents in the SPADE platform (which is indeed made by us). We have chosen your package to create our bdi agents, and as a result we will soon publish the SPADE extension for BDI agents.

**Pull request closed without merging**
